before_script:
    - pip install tox

stages:
  - test

.python3.9_image: &py39
  image: registry.nic.cz/turris/turrishw/python3.9

lint:
  <<: *py39
  stage: test
  script:
    - tox -e lint

python3.9:
  <<: *py39
  stage: test
  script:
    - tox -e py39
